application:
  static:
    resources:
      patterns: "d:\\other projects\\mockapp\\static resources\\patterns"
      scenarios: "d:\\other projects\\mockapp\\static resources\\scenarios"
      scripts: "d:\\other projects\\mockapp\\static resources\\scripts"
      templates: "d:\\other projects\\mockapp\\static resources\\templates"
server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1
  jetty:
    acceptors: 2

